version: '3'
services:
  ucs:
    build: docker_ucs/
    ports:
      - "9998:9998"
    networks:
      backend:
        ipv4_address: 10.0.0.3        
  pep:
    build: docker_pep/
    ports: 
      - "9999:9999"
    networks:
      backend:
        ipv4_address: 10.0.0.5
networks:
  backend:
    ipam:
     config:
       - subnet: 10.0.0.0/16
